### ISSUE TITLE
v7.0.0-rc.1 requires Firebird 4.0+ headers - cannot compile with Firebird 3.0 client

### ISSUE THREAD

**Issue by satwareAG-ironMike** [satwareAG/php-firebird#19]
## Problem

When attempting to compile php-firebird v7.0.0-rc.1 with Firebird 3.0 client libraries (installed via IBSurgeon `fb_vanilla-30.sh`), the build fails with:

```
/tmp/php-firebird/src/cpp/fb_array.hpp:35:10: fatal error: firebird/impl/blr.h: No such file or directory
   35 | #include <firebird/impl/blr.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:251: firebird_utils.lo] Error 1
```

## Environment

- PHP: 8.1-8.5 (tested on GitHub Actions with `php:X.Y-cli-bookworm`)
- Firebird Server: 3.0 (also tested with 2.5, 4.0, 5.0)
- Firebird Client: Installed via IBSurgeon scripts (`fb_vanilla-30.sh`)
- OS: Debian Bookworm (Ubuntu-latest runners)

## Analysis

The `firebird/impl/blr.h` header file is part of the **Firebird 4.0+** client development headers. The Firebird 3.0 client installation does not include this subdirectory structure.

Firebird 3.0 headers are typically at:
- `/opt/firebird/include/ibase.h`
- `/opt/firebird/include/iberror.h`

Firebird 4.0+ headers include additional paths:
- `/opt/firebird/include/firebird/impl/blr.h`
- `/opt/firebird/include/firebird/impl/sql.h`

## Expected Behavior

php-firebird v7.0.0 should compile successfully using **Firebird 3.0 client libraries**, since:
1. Many production systems still run Firebird 3.0
2. The PHP extension should support connecting to all supported Firebird versions (2.5, 3.0, 4.0, 5.0)
3. The previous v6.2.0 compiles successfully against Firebird 3.0 headers

## Proposed Solutions

1. **Add conditional compilation** to support both Firebird 3.x and 4.x+ headers
2. **Provide fallback definitions** for `blr.h` types when the header is missing
3. **Document minimum Firebird client version** if v7.0.0 intentionally drops Firebird 3.0 client support

## Workaround

Currently using v6.2.0 which compiles against all Firebird versions.

## References

- doctrine-firebird-driver CI failure: https://github.com/satwareAG/doctrine-firebird-driver/actions
- IBSurgeon install scripts: https://github.com/IBSurgeon/firebirdlinuxinstall

**Comment by satwareAG-ironMike** [comment]
Fixed with `fb_blr_compat.h` header providing fallback BLR constant definitions. Additional runtime fix in rc.3 changed all error checks in `fb_connection.hpp` to use `hasData()` instead of `isDirty()` for proper FB3 compatibility.

CI verification: All 20 jobs passed including PHP 8.1-8.5 × Firebird 3.0 tests.
